#!/usr/bin/env python3
"""Convert a modern deck export into the old PTCGO import format.

Three input layouts are accepted:

1. Limitless "Copy to Clipboard" / site export (already has set codes)::

    Pokemon: 16
    4 Sobble CRE 41
    ...
    Trainer: 34
    4 Professor's Research SHF 60
    ...
    Energy: 10
    10 Metal Energy Energy 43

2. Limitless rendered page text (headers in parens, '(SET-NUM)' on card
   lines, trainers/energies with no set code)::

    Pokémon (16)

    4 Sobble (CRE-41)
    ...
    Trainer (34)

    4 Professor's Research
    ...
    Energy (10)

    10 Grass Energy

   Trainers and energies without a set/number are filled from the local
   card catalog (spirit/game/scripts/cards), so the result is importable
   in the client.  Every filled line gets a warning; lines the catalog
   cannot resolve are left alone (and warned about).  Basic energies use
   the client's 'Energy' collector numbers (Grass 36 .. Fairy 44).

   Tip: Limitless' Copy to Clipboard button already gives layout 1, which
   needs no filling.

3. Old (the format the client still imports) -- also accepted, normalised
   idempotently::

    ****** Pokemon Trading Card Game Deck List ******
    ##Pokemon - 16

    * 4 Sobble CRE 41
    ...

    ##Trainer Cards - 34

    * 4 Professor's Research SHF 60
    ...

    ##Energy - 10

    * 10 Metal Energy 43

    Total Cards - 60

    ****** Deck List Generated by the Pokemon TCG Online www.pokemon.com/TCGO ******

Usage:
    python tools/convert_deck.py deck.txt            # converted list to stdout
    python tools/convert_deck.py deck.txt -o out.txt
    python tools/convert_deck.py deck.txt --to-decks # also save as spirit/tools/DECKS/<first Pokemon>.txt
    python tools/convert_deck.py - < deck.txt        # read stdin
    cat deck.txt | python tools/convert_deck.py -o out.txt

Already-old input is normalised (idempotent), so re-running on an old file is safe.
"""
import argparse
import html
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DECKS_DIR = ROOT / "spirit" / "tools" / "DECKS"

HEADER_RE = re.compile(
    r"^\s*#{0,6}\s*(Pok.?mon|Trainer(?:\s+Cards?)?|Energy)"
    r"\s*(?:[:\-]\s*(\d+)?|\(\s*(\d+)\s*\))\s*$",
    re.IGNORECASE,
)
CARD_RE = re.compile(r"^\s*\*?\s*(\d+)\s+(\S.*\S)\s*$")
# Trailing '(SET-NUM)' from rendered Limitless lists -> 'SET NUM'.
PAREN_SET_RE = re.compile(r"^(.*\S)\s+\(([A-Za-z0-9]+)-([A-Za-z0-9]+)\)\s*$")
# 'Metal Energy Energy 43' -> name already ends in Energy, drop the extra word.
ENERGY_DUP_RE = re.compile(r"^(.*\S)\s+Energy\s+(\d+)$", re.IGNORECASE)
SET_CODE_RE = re.compile(r"^[A-Za-z][A-Za-z0-9\-]{1,10}$")
IGNORED_RE = re.compile(
    r"^\s*(?:\*{4,}.*|#{2,}\s*.*#\s*$|Total\s+Cards\s*[:\-].*|Pok.?mon\s+Trading\s+Card\s+Game.*)$",
    re.IGNORECASE,
)

SECTION_ORDER = ["pokemon", "trainer", "energy"]
SECTION_TITLE = {"pokemon": "Pokémon", "trainer": "Trainer Cards", "energy": "Energy"}


def section_key(header_name: str) -> str:
    # Accept 'Pokémon', 'Pokemon', or console-mangled 'Pok?mon'/'Pokmon'.
    name = re.sub(r"[^a-z]", "", header_name.lower().replace("?", "e"))
    if name in {"pokmon"}:
        name = "pokemon"
    if name.startswith("pokemon"):
        return "pokemon"
    if name.startswith("trainer"):
        return "trainer"
    return "energy"


def strip_paren_set(line: str) -> str:
    """'4 Sobble (CRE-41)' -> '4 Sobble CRE 41' (rendered Limitless lists)."""
    return PAREN_SET_RE.sub(r"\1 \2 \3", line)


# Client 'Energy' set collector numbers for the nine basic energies, as used
# by Limitless' clipboard text and the decks already in spirit/tools/DECKS.
BASIC_ENERGY_NUMBERS = {
    "grass energy": 36, "fire energy": 37, "water energy": 38,
    "lightning energy": 39, "psychic energy": 40, "fighting energy": 41,
    "darkness energy": 42, "metal energy": 43, "fairy energy": 44,
}

_CATALOG = None
_CATALOG_UNAVAILABLE = False


def _load_catalog():
    """spirit/tools/build_bot_decks (card catalog + set maps), loaded on demand."""
    global _CATALOG, _CATALOG_UNAVAILABLE
    if _CATALOG is not None:
        return _CATALOG
    if _CATALOG_UNAVAILABLE:
        return None
    try:
        tools = ROOT / "spirit" / "tools"
        if str(tools) not in sys.path:
            sys.path.insert(0, str(tools))
        import build_bot_decks
        _CATALOG = build_bot_decks
    except Exception:
        _CATALOG_UNAVAILABLE = True
    return _CATALOG


def _pick_card(name: str, set_hint: str = None):
    cat = _load_catalog()
    if cat is None:
        return None
    try:
        card, _cands = cat.pick(name, set_hint)
    except Exception:
        return None
    return card


def _live_ref(card) -> tuple:
    """(live set code, collector number) for output, or (None, None)."""
    cat = _load_catalog()
    live = cat.LIVE_CODE.get(card.key)
    num = card.get_attribute_value(cat.AttrID.COLLECTOR_NUMBER)
    return (live, num) if live is not None and num is not None else (None, None)


def _local_hint(token: str):
    cat = _load_catalog()
    if cat is None:
        return None
    return cat.SET_CODE_MAP.get(token.upper(), token.upper())


def _fill_missing_set(rest: str, count: int, warnings: list, line: str):
    """Resolve a set-less pokemon/trainer line against the card catalog."""
    tokens = rest.split()
    name = " ".join(tokens[:-1]) if tokens and tokens[-1].isdigit() else rest
    card = _pick_card(name)
    if card is None:
        hint_tokens = tokens[:-1] if tokens and tokens[-1].isdigit() else tokens
        if len(hint_tokens) > 1 and SET_CODE_RE.match(hint_tokens[-1]) \
                and hint_tokens[-1].lower() != "energy":
            short = " ".join(hint_tokens[:-1])
            card = _pick_card(short, _local_hint(hint_tokens[-1]))
            if card is not None:
                name = short
    if card is None:
        return None
    live, num = _live_ref(card)
    if live is None:
        return None
    ref = f"{name} {live} {num}"
    full = f"{count} {ref}"
    warnings.append(f"filled from card catalog: {line!r} -> {full!r}")
    return ref


def _fill_missing_energy(rest: str, count: int, warnings: list, line: str):
    """Resolve a set-less energy line: catalog for special, table for basic."""
    tokens = rest.split()
    name = rest
    card = _pick_card(name)
    if card is None and len(tokens) > 1 and SET_CODE_RE.match(tokens[-1]) \
            and tokens[-1].lower() != "energy":
        short = " ".join(tokens[:-1])
        card = _pick_card(short, _local_hint(tokens[-1]))
        if card is not None:
            name = short
    cat = _load_catalog()
    if card is not None and cat is not None and not cat.is_basic_energy(card):
        live, num = _live_ref(card)
        if live is None:
            return None
        ref = f"{count} {name} {live} {num}"
        warnings.append(f"filled from card catalog: {line!r} -> {ref!r}")
        return f"{name} {live} {num}"
    number = BASIC_ENERGY_NUMBERS.get(
        re.sub(r"\s+", " ", name).strip().lower())
    if number is not None:
        ref = f"{count} {name} {number}"
        warnings.append(f"filled basic energy number: {line!r} -> {ref!r}")
        return f"{name} {number}"
    return None


def normalise_card_line(section: str, line: str, warnings: list) -> str:
    m = CARD_RE.match(line)
    if not m:
        warnings.append(f"skipped unparsable line: {line!r}")
        return ""
    count, rest = int(m.group(1)), m.group(2)

    def _note() -> str:
        return "" if _load_catalog() is not None else " (card catalog unavailable)"

    if section == "energy":
        dup = ENERGY_DUP_RE.match(rest)
        if dup and dup.group(1).lower().endswith("energy"):
            rest = f"{dup.group(1)} {dup.group(2)}"
        elif not rest.split()[-1].isdigit():
            filled = _fill_missing_energy(rest, count, warnings, line)
            if filled:
                rest = filled
            else:
                warnings.append(
                    f"energy line has no collector number:{_note()} {line!r}")
    else:
        tokens = rest.split()
        if len(tokens) < 3 or not tokens[-1].isdigit() or not SET_CODE_RE.match(tokens[-2]):
            filled = _fill_missing_set(rest, count, warnings, line)
            if filled:
                rest = filled
            else:
                warnings.append(
                    f"line looks like it is missing a set code:{_note()} {line!r}")
    return f"* {count} {rest}"


def convert(text: str, ascii_only: bool = False, decode_entities: bool = False) -> tuple:
    """Return (converted_text, warnings, section_counts, total)."""
    # The client expects site names verbatim -- 'Jessie &amp; James' stays
    # escaped, decoding it breaks the import. Opt in only with --decode-entities.
    if decode_entities:
        text = html.unescape(text)
    sections: dict = {k: [] for k in SECTION_ORDER}
    current = None
    header_counts: dict = {}
    warnings: list = []

    for raw in text.splitlines():
        line = strip_paren_set(raw.rstrip())
        if not line.strip():
            continue
        head = HEADER_RE.match(line)
        if head:
            current = section_key(head.group(1))
            stated = head.group(2) or head.group(3)
            if stated:
                header_counts[current] = int(stated)
            continue
        if IGNORED_RE.match(line):
            continue
        if current is None:
            warnings.append(f"card line before any section header: {line!r}")
            continue
        card = normalise_card_line(current, line, warnings)
        if card:
            sections[current].append(card)

    counts = {k: sum(int(CARD_RE.match(c).group(1)) for c in sections[k])
              for k in SECTION_ORDER}
    total = sum(counts.values())
    for key, stated in header_counts.items():
        if stated != counts[key]:
            warnings.append(
                f"{SECTION_TITLE[key]}: header says {stated}, lines add up to {counts[key]}")
    if total != 60:
        warnings.append(f"Total Cards - {total} (expected 60)")

    out = ["****** Pokémon Trading Card Game Deck List ******"]
    for i, key in enumerate(SECTION_ORDER):
        if i:
            out.append("")
        out.append(f"##{SECTION_TITLE[key]} - {counts[key]}")
        out.append("")
        out.extend(sections[key])
    out.append("")
    out.append(f"Total Cards - {total}")
    out.append("")
    out.append("****** Deck List Generated by the Pokémon TCG Online www.pokemon.com/TCGO ******")
    body = "\n".join(out) + "\n"
    if ascii_only:
        body = body.replace("é", "e")
    return body, warnings, counts, total


def _split_card(section: str, count: str, rest: str) -> tuple:
    """(count, name, set_code, number) from one card line's body."""
    tokens = rest.split()
    number = tokens[-1] if tokens and tokens[-1].isdigit() else None
    body = tokens[:-1] if number else tokens
    if body and len(body) > 1 and SET_CODE_RE.match(body[-1]) \
            and body[-1].lower() != "energy":
        return int(count), " ".join(body[:-1]), body[-1], number
    if number is None and body and len(body) > 1 and SET_CODE_RE.match(body[-1]):
        return int(count), " ".join(body[:-1]), body[-1], None
    name = " ".join(body)
    if name.lower().endswith(" energy energy"):  # raw site text, pre-conversion
        name = name[: -(len(" energy"))]
    return int(count), name, None, number


def parse_card_lines(text: str) -> list:
    """Structured view of a deck list: [(section, count, name, set, number)].

    set_code is None when the line carries no set (e.g. '3 Psychic Energy 40'),
    number is None when the collector number is not numeric (e.g. 'SSH P').
    Names come through byte-for-byte, entities included.
    """
    rows = []
    current = None
    for raw in text.splitlines():
        line = strip_paren_set(raw.rstrip())
        if not line.strip():
            continue
        head = HEADER_RE.match(line)
        if head:
            current = section_key(head.group(1))
            continue
        if current is None or IGNORED_RE.match(line):
            continue
        m = CARD_RE.match(line)
        if not m:
            continue
        rows.append((current,) + _split_card(current, m.group(1), m.group(2)))
    return rows


def first_pokemon_name(converted: str) -> str:
    """Name for the saved deck file: the first Pokemon listed, e.g. 'Zorua'."""
    in_pokemon = False
    for line in converted.splitlines():
        head = HEADER_RE.match(line)
        if head:
            in_pokemon = section_key(head.group(1)) == "pokemon"
            continue
        if not in_pokemon:
            continue
        card = CARD_RE.match(line)
        if not card:
            continue
        tokens = card.group(2).split()
        if len(tokens) >= 3 and tokens[-1].isdigit() and SET_CODE_RE.match(tokens[-2]):
            tokens = tokens[:-2]
        elif tokens and tokens[-1].isdigit():
            tokens = tokens[:-1]
        name = " ".join(tokens).strip()
        for ch in '\\/:*?"<>|':
            name = name.replace(ch, "")
        return name
    return ""


def main(argv=None) -> int:
    for stream in (sys.stdout, sys.stderr):
        try:
            stream.reconfigure(encoding="utf-8", errors="replace")
        except Exception:
            pass
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("input", help="deck file, or '-' for stdin")
    ap.add_argument("-o", "--output", help="write here instead of stdout")
    ap.add_argument("--ascii", action="store_true",
                    help="write 'Pokemon' instead of 'Pokémon' (fallback for the client)")
    ap.add_argument("--decode-entities", action="store_true",
                    help="turn '&amp;' into '&' (off by default: the client wants the "
                         "escaped names as-is)")
    ap.add_argument("--to-decks", action="store_true",
                    help="also save into spirit/tools/DECKS/<first Pokemon>.txt")
    args = ap.parse_args(argv)

    if args.input == "-":
        text = sys.stdin.buffer.read().decode("utf-8-sig", errors="replace")
    else:
        with open(args.input, encoding="utf-8-sig") as fh:
            text = fh.read()

    converted, warnings, counts, total = convert(text, ascii_only=args.ascii,
                                                 decode_entities=args.decode_entities)
    dests = []
    if args.output:
        with open(args.output, "w", encoding="utf-8", newline="\n") as fh:
            fh.write(converted)
        dests.append(args.output)
    else:
        sys.stdout.write(converted)
        dests.append("stdout")
    if args.to_decks:
        name = first_pokemon_name(converted)
        if not name:
            warnings.append("no Pokemon found to name the deck file")
        else:
            DECKS_DIR.mkdir(parents=True, exist_ok=True)
            path = DECKS_DIR / f"{name}.txt"
            with open(path, "w", encoding="utf-8", newline="\n") as fh:
                fh.write(converted)
            dests.append(str(path))
    for w in warnings:
        print(f"warning: {w}", file=sys.stderr)
    print(f"Pokemon {counts['pokemon']}, Trainer {counts['trainer']}, "
          f"Energy {counts['energy']}, Total {total} -> {', '.join(dests)}",
          file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
